### ISSUE TITLE
What version Python should be used?

### ISSUE THREAD

**Issue by smcpoland** [Asbaek/openisms#5]
What version Python should be used?

I'm using the latest 3.7, and having issues.

Many thanks

**Comment by weathrman** [comment]
Python 3.7 should be a stable release. What operating system are you using?

**Comment by smcpoland** [comment]
Windows 10...latest updates.

I've installed Anaconda from conda (64 bit) and Visual Code.

Took a while to sort out issues with spaces and tabs...a python enforcement.

There was a TRY...EXCEPT issue

try:
except  KeyError, e:

I had to change to

except  KeyError as e:

Thanks...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smcpoland** [comment]
also when I execute according to the Wiki I get the following error:

C:\Users\????\Downloads\openisms-master>python openisms.py
Traceback (most recent call last):
  File "openisms.py", line 1079, in <module>
    fix_data_structure()
  File "openisms.py", line 81, in fix_data_structure
    fixed_process = fix_json_dict(schema['processes'][0],process)
  File "openisms.py", line 52, in fix_json_dict
    for rkey, rvalue in reference_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

And on further investigation the cmp function is no longer valid in Python 3... changed as follows

**old**:
if cmp(var_dict, risk_dict)==0:

**new**:
if cmp_to_symbol(var_dict, risk_dict)==0:

**added the following function**
def cmp_to_symbol(val, other_val):
    '''returns the symbol representing the relationship between two values'''
    return '=><'[(val > other_val) - (val < other_val)]


I would try to pull and fix but I know very little about python or using github.

**Comment by azfarbaig** [comment]
I am having issue while applying the command, below error reported.

On line 92
TabError: inconsistent use of tabs and spaces in indentation

**Comment by azfarbaig** [comment]
Exact Error:

File "openisms.py", line 92
    if impact_type:
                  ^
TabError: inconsistent use of tabs and spaces in indentation
